### ISSUE TITLE
Unable to register for API key

### ISSUE THREAD

**Issue by abcnishant007** [zach401/ACN-Sim-Demo#8]
hi @zach401 /@tongxin-li /@sunash, just read your ACN (IEEE smart grid) paper. Congrats on the paper and thanks for this amazing codebase! It is really heartwarming to see this kind of clean and reusable (and not just reproducible) code accompanying a paper! 

I am trying to use your code for my paper. I tried to get a Key from the [ACN](https://ev.caltech.edu/) website. I guess there is something wrong with the app. The registration button works, but then it gets stuck and throws a message later on Screenshot attached below. 
<img width="320" alt="Screenshot 2022-08-09 at 14 27 47" src="https://user-images.githubusercontent.com/9101260/183579705-8e9af52e-8c57-440d-86de-99a8bdfd1a24.png">

Is it possible to fix this issue?

**Comment by zach401** [comment]
Unfortunately our registration service is down right now. In the mean time, you can use our sample token "DEMO_TOKEN" to access the dataset.

**Comment by abcnishant007** [comment]
@zach401, thanks for the update. The DEMO_TOEKN works!!  
Please feel free to close the issue.
