### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.mixture.gaussian_mixture'

### ISSUE THREAD

**Issue by AaronFAN20x3** [zach401/ACN-Sim-Demo#9]
Hi @zach401,  @tongxin-li , @sunash. Thanks for this amazing codebase.
I'm very interested in acnportal-experiments example. And I tried to run the code on Colab Link from README, but I got an error
![9f6e11ac8cbd6c88db6c5d89d2920f0](https://user-images.githubusercontent.com/96039896/185951199-e7d5bf60-27f0-47cd-ae82-fa859718b001.png)
ModuleNotFoundError: No module named 'sklearn.mixture.gaussian_mixture' 
I tried to add from sklearn.mixture import _gaussian_mixture as gaussian_mixture but it still posts the same error
wondering if any chance to have some advice about how to solve this, please?
Thanks again!

**Comment by abcnishant007** [comment]
@AaronFAN20x3 I had the same issue but I was able to run by downgrading my sklearn. https://stackoverflow.com/a/60144921/3896008 
Maybe that works for you too!
